variables:
  - name: Build.Repository.Clean
    value: true
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _HelixType
    value: build/product
  - name: _DotNetArtifactsCategory
    value: .NETCore

  # Variables for public PR builds
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - name: _HelixSource
      value: pr/aspnet/AspLabs/$(Build.SourceBranch)

  # Variables for internal Official builds
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - name: _HelixSource
      value: official/aspnet/AspLabs/$(Build.SourceBranch)

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools-prereqs:ubuntu-18.04-c103199-20180628134610
    options: --init # This ensures all the stray defunct processes are reaped.

trigger:
- main

pr:
- "*"

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      helixRepo: aspnet/AspLabs
      # enableMicrobuild can't be read from a user-defined variable (Azure DevOps limitation)
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        enableMicrobuild: true
      jobs:
      - job: Windows
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Public
            demands: ImageOverride -equals Build.Server.Amd64.VS2017.Open
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals Build.Server.Amd64.VS2017
        variables:
        - name: _HelixBuildConfig
          value: $(_BuildConfig)
        strategy:
          matrix:
            ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
              Debug:
                _BuildConfig: Debug
                _SignType: test
                _BuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
            Release:
              _BuildConfig: Release
              # PRs and external builds are not signed.
              ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
                _SignType: test
                _BuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
              ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
                _SignType: real
                _BuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:OfficialBuildId=$(Build.BuildNumber)
                  /p:DotNetPublishUsingPipelines=true
                  /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                  /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
                  /p:DotNetPublishToBlobFeed=true
        steps:
        - checkout: self
          clean: true
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
        - task: NuGetCommand@2
          displayName: 'Clear NuGet caches'
          condition: succeeded()
          inputs:
            command: custom
            arguments: 'locals all -clear'
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
            $(_BuildArgs)
          name: Build
          displayName: Build
          condition: succeeded()
        - task: PublishTestResults@2
          displayName: Publish xUnit Test Results
          condition: always()
          continueOnError: true
          inputs:
            testRunner: xunit
            testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'
        - task: PublishBuildArtifacts@1
          displayName: Publish Packages
          condition: and(eq(variables['system.pullrequest.isfork'], false), eq(variables['_BuildConfig'], 'Release'))
          continueOnError: true
          inputs:
            artifactName: Packages_$(Agent.Os)_$(Agent.JobName)
            parallel: true
            pathtoPublish: '$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)'
            publishLocation: Container
        - task: PublishBuildArtifacts@1
          displayName: Publish Logs
          condition: always()
          continueOnError: true
          inputs:
            artifactName: Logs_$(Agent.Os)_$(Agent.JobName)
            parallel: true
            pathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
            publishLocation: Container

      - job: macOS
        pool:
          vmImage: macOS-10.15
        strategy:
          matrix:
            debug:
              _BuildConfig: Debug
            release:
              _BuildConfig: Release
        variables:
        - name: _HelixBuildConfig
          value: $(_BuildConfig)
        steps:
        - checkout: self
          clean: true
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
          name: Build
          displayName: Build
          condition: succeeded()
        - task: PublishTestResults@2
          displayName: Publish xUnit Test Results
          condition: always()
          continueOnError: true
          inputs:
            testRunner: xunit
            testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'
        - task: PublishBuildArtifacts@1
          displayName: Publish Logs
          condition: always()
          continueOnError: true
          inputs:
            artifactName: Logs_$(Agent.Os)_$(Agent.JobName)
            parallel: true
            pathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
            publishLocation: Container

      - job: Linux
        pool:
          vmImage: ubuntu-18.04
          container: LinuxContainer
        strategy:
          matrix:
            debug:
              _BuildConfig: Debug
            release:
              _BuildConfig: Release
        variables:
        - name: _HelixBuildConfig
          value: $(_BuildConfig)
        steps:
        - checkout: self
          clean: true
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
          name: Build
          displayName: Build
          condition: succeeded()
        - task: PublishTestResults@2
          displayName: Publish xUnit Test Results
          condition: always()
          continueOnError: true
          inputs:
            testRunner: xunit
            testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'
        - task: PublishBuildArtifacts@1
          displayName: Publish Logs
          condition: always()
          continueOnError: true
          inputs:
            artifactName: Logs_$(Agent.Os)_$(Agent.JobName)
            parallel: true
            pathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
            publishLocation: Container

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: eng\common\templates\post-build\post-build.yml
    parameters:
      publishingInfraVersion: 3
      # Symbol validation isn't being very reliable lately. This should be enabled back
      # once this issue is resolved: https://github.com/dotnet/arcade/issues/2871
      enableSymbolValidation: false
      # This is to enable SDL runs part of Post-Build Validation Stage
      SDLValidationParameters:
        enable: false
name: Build
on:
  push:
    branches:
      - master # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"ggg" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
